services:
  postgres:
    image: postgres:16.13-trixie # PINNED! Do not update outside MX-2398
    environment:
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD: dagster
      POSTGRES_DB: dagster
    volumes:
      - pgdata:/var/lib/postgresql/data
  dagster-daemon:
    build:
      context: .
    entrypoint: [ "dagster-daemon", "run", "-w", "workspace.yaml" ]
    depends_on:
      - postgres
    volumes:
      - ./dagster-compose.yaml:/app/dagster/dagster.yaml:ro
      - dagster:/app/work:rw
  dagster-webserver:
    build:
      context: .
    ports:
      - 3000:3000
    entrypoint: [ "dagster-webserver", "--host", "0.0.0.0", "-w", "workspace.yaml" ]
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/dagit_info" ]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
    volumes:
      - ./dagster-compose.yaml:/app/dagster/dagster.yaml:ro
      - dagster:/app/work:rw
  slapd:
    image: thoteam/slapd-server-mock
    ports:
      - 636:636
    volumes:
      - ./assets/raw-data/ldap/:/bootstrap/
    expose:
      - 636
  mailpit:
    image: axllent/mailpit:v1.30
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_UI_AUTH=user:password
    expose:
      - 8025
  neo4j:
    image: neo4j:2026.07-community@sha256:dca31d0d938dd8bb199c8846abedd897c3a07ddb629eca46a8009ac9e87aece2
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_usage__report_enabled=false
    ports:
      - 7687:7687
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  mex-backend:
    image: ghcr.io/robert-koch-institut/mex-backend:4.2.2
    entrypoint: testing-backend
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - MEX_GRAPH_URL=neo4j://neo4j:7687
      - MEX_BACKEND_API_KEY_DATABASE={"write":["write_key"]}
      - MEX_DEBUG=true
    expose:
      - 8080
volumes:
  pgdata:
  dagster:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: mode=1777
